-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le : mer. 19 jan. 2022 à 16:39
-- Version du serveur :  8.0.21
-- Version de PHP : 7.3.21

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `projet-blog`
--

-- --------------------------------------------------------

--
-- Structure de la table `articles`
--

DROP TABLE IF EXISTS `articles`;
CREATE TABLE IF NOT EXISTS `articles` (
  `id_article` int NOT NULL AUTO_INCREMENT,
  `title` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `content` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `image` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `id_category` int NOT NULL,
  `id_user` int NOT NULL,
  PRIMARY KEY (`id_article`)
) ENGINE=MyISAM AUTO_INCREMENT=41 DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `articles`
--

INSERT INTO `articles` (`id_article`, `title`, `content`, `image`, `id_category`, `id_user`) VALUES
(1, 'Cinque Terre', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tellus non pellentesque molestie dui mauris faucibus sit. Lacus mauris, integer dignissim mauris. Mattis tempor enim diam et sapien. Volutpat sit sapien faucibus aliquam. Velit tortor vivamus lectus fusce. Aliquam, enim phasellus a et, pellentesque. Bibendum est adipiscing dolor mattis tellus vel. Ut amet in vitae consequat amet. Pharetra vel porta posuere velit arcu aenean eget. Morbi quis massa euismod nunc fusce sit nulla leo. Aliquam et massa ac urna, sem tristique habitant pellentesque. Nec magna risus quis tincidunt fermentum ut id sed. Cursus adipiscing accumsan tempus, leo neque. Ut placerat at commodo accumsan, porta consectetur dictum.\r\nId vitae commodo lacus tellus. Tincidunt adipiscing bibendum turpis nam pellentesque quis leo. Sed viverra volutpat scelerisque eu morbi natoque non magna. Facilisis volutpat vel, tortor laoreet porttitor ullamcorper massa placerat diam. Iaculis varius lorem ullamcorper a in nulla dolor gravida feugiat. Pharetra justo et pellentesque nunc pretium ut blandit ultricies porttitor. Lacinia sit congue dui ante neque, enim duis id. Auctor nullam purus enim quam posuere.\r\nEros vestibulum nisl quam est luctus fames consectetur bibendum. Nunc, blandit nibh dui cursus metus mi vulputate. Risus sed eu vitae viverra mi congue proin vulputate. Sociis volutpat cursus et adipiscing auctor. Elit magna lacus quis sit fermentum. Eget praesent tellus non nulla.\r\nMassa et congue non dictum. Egestas cursus arcu proin sed in. Eros, volutpat odio in in diam accumsan. Semper sed hac id in ipsum in. Massa malesuada ac mauris consequat. Gravida tincidunt a pellentesque posuere amet pulvinar egestas. Ipsum orci aliquet urna, vitae egestas. Turpis leo magna ultrices odio proin semper tempus. Sem sit sit sed turpis eu donec quis. Dui sed pellentesque scelerisque etiam sollicitudin.\r\nVel volutpat bibendum ullamcorper commodo tempor quam sed arcu malesuada. At dignissim mattis ornare sem turpis dictum ultrices mi sed. Arcu in condimentum urna, molestie mattis. Cursus nulla cursus gravida porttitor diam, neque enim, sit. Pretium vulputate pellentesque purus sociis pellentesque egestas est urna.\r\nArcu adipiscing consequat, sit felis dictum. Amet adipiscing ut nibh at nibh. Id gravida lectus praesent neque eu lectus quisque. Dolor faucibus leo, at consequat neque. Risus mi sed augue diam. Libero molestie nulla sociis nisl massa libero, sollicitudin. Ut morbi etiam ut massa malesuada. Tristique tellus adipiscing diam sed. ', './img/01_cinque_terre.jpg', 1, 1),
(2, 'Tsavo East', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tellus non pellentesque molestie dui mauris faucibus sit. Lacus mauris, integer dignissim mauris. Mattis tempor enim diam et sapien. Volutpat sit sapien faucibus aliquam. Velit tortor vivamus lectus fusce. Aliquam, enim phasellus a et, pellentesque. Bibendum est adipiscing dolor mattis tellus vel. Ut amet in vitae consequat amet. Pharetra vel porta posuere velit arcu aenean eget. Morbi quis massa euismod nunc fusce sit nulla leo. Aliquam et massa ac urna, sem tristique habitant pellentesque. Nec magna risus quis tincidunt fermentum ut id sed. Cursus adipiscing accumsan tempus, leo neque. Ut placerat at commodo accumsan, porta consectetur dictum.\r\nId vitae commodo lacus tellus. Tincidunt adipiscing bibendum turpis nam pellentesque quis leo. Sed viverra volutpat scelerisque eu morbi natoque non magna. Facilisis volutpat vel, tortor laoreet porttitor ullamcorper massa placerat diam. Iaculis varius lorem ullamcorper a in nulla dolor gravida feugiat. Pharetra justo et pellentesque nunc pretium ut blandit ultricies porttitor. Lacinia sit congue dui ante neque, enim duis id. Auctor nullam purus enim quam posuere.\r\nEros vestibulum nisl quam est luctus fames consectetur bibendum. Nunc, blandit nibh dui cursus metus mi vulputate. Risus sed eu vitae viverra mi congue proin vulputate. Sociis volutpat cursus et adipiscing auctor. Elit magna lacus quis sit fermentum. Eget praesent tellus non nulla.\r\nMassa et congue non dictum. Egestas cursus arcu proin sed in. Eros, volutpat odio in in diam accumsan. Semper sed hac id in ipsum in. Massa malesuada ac mauris consequat. Gravida tincidunt a pellentesque posuere amet pulvinar egestas. Ipsum orci aliquet urna, vitae egestas. Turpis leo magna ultrices odio proin semper tempus. Sem sit sit sed turpis eu donec quis. Dui sed pellentesque scelerisque etiam sollicitudin.\r\nVel volutpat bibendum ullamcorper commodo tempor quam sed arcu malesuada. At dignissim mattis ornare sem turpis dictum ultrices mi sed. Arcu in condimentum urna, molestie mattis. Cursus nulla cursus gravida porttitor diam, neque enim, sit. Pretium vulputate pellentesque purus sociis pellentesque egestas est urna.\r\nArcu adipiscing consequat, sit felis dictum. Amet adipiscing ut nibh at nibh. Id gravida lectus praesent neque eu lectus quisque. Dolor faucibus leo, at consequat neque. Risus mi sed augue diam. Libero molestie nulla sociis nisl massa libero, sollicitudin. Ut morbi etiam ut massa malesuada. Tristique tellus adipiscing diam sed. ', '.\\img\\02_tsavo_east.jpg', 2, 1),
(3, 'San Francisco', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tellus non pellentesque molestie dui mauris faucibus sit. Lacus mauris, integer dignissim mauris. Mattis tempor enim diam et sapien. Volutpat sit sapien faucibus aliquam. Velit tortor vivamus lectus fusce. Aliquam, enim phasellus a et, pellentesque. Bibendum est adipiscing dolor mattis tellus vel. Ut amet in vitae consequat amet. Pharetra vel porta posuere velit arcu aenean eget. Morbi quis massa euismod nunc fusce sit nulla leo. Aliquam et massa ac urna, sem tristique habitant pellentesque. Nec magna risus quis tincidunt fermentum ut id sed. Cursus adipiscing accumsan tempus, leo neque. Ut placerat at commodo accumsan, porta consectetur dictum.\r\nId vitae commodo lacus tellus. Tincidunt adipiscing bibendum turpis nam pellentesque quis leo. Sed viverra volutpat scelerisque eu morbi natoque non magna. Facilisis volutpat vel, tortor laoreet porttitor ullamcorper massa placerat diam. Iaculis varius lorem ullamcorper a in nulla dolor gravida feugiat. Pharetra justo et pellentesque nunc pretium ut blandit ultricies porttitor. Lacinia sit congue dui ante neque, enim duis id. Auctor nullam purus enim quam posuere.\r\nEros vestibulum nisl quam est luctus fames consectetur bibendum. Nunc, blandit nibh dui cursus metus mi vulputate. Risus sed eu vitae viverra mi congue proin vulputate. Sociis volutpat cursus et adipiscing auctor. Elit magna lacus quis sit fermentum. Eget praesent tellus non nulla.\r\nMassa et congue non dictum. Egestas cursus arcu proin sed in. Eros, volutpat odio in in diam accumsan. Semper sed hac id in ipsum in. Massa malesuada ac mauris consequat. Gravida tincidunt a pellentesque posuere amet pulvinar egestas. Ipsum orci aliquet urna, vitae egestas. Turpis leo magna ultrices odio proin semper tempus. Sem sit sit sed turpis eu donec quis. Dui sed pellentesque scelerisque etiam sollicitudin.\r\nVel volutpat bibendum ullamcorper commodo tempor quam sed arcu malesuada. At dignissim mattis ornare sem turpis dictum ultrices mi sed. Arcu in condimentum urna, molestie mattis. Cursus nulla cursus gravida porttitor diam, neque enim, sit. Pretium vulputate pellentesque purus sociis pellentesque egestas est urna.\r\nArcu adipiscing consequat, sit felis dictum. Amet adipiscing ut nibh at nibh. Id gravida lectus praesent neque eu lectus quisque. Dolor faucibus leo, at consequat neque. Risus mi sed augue diam. Libero molestie nulla sociis nisl massa libero, sollicitudin. Ut morbi etiam ut massa malesuada. Tristique tellus adipiscing diam sed. ', '.\\img\\03_san_francisco.jpg', 3, 1),
(4, 'Fujiyoshida', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tellus non pellentesque molestie dui mauris faucibus sit. Lacus mauris, integer dignissim mauris. Mattis tempor enim diam et sapien. Volutpat sit sapien faucibus aliquam. Velit tortor vivamus lectus fusce. Aliquam, enim phasellus a et, pellentesque. Bibendum est adipiscing dolor mattis tellus vel. Ut amet in vitae consequat amet. Pharetra vel porta posuere velit arcu aenean eget. Morbi quis massa euismod nunc fusce sit nulla leo. Aliquam et massa ac urna, sem tristique habitant pellentesque. Nec magna risus quis tincidunt fermentum ut id sed. Cursus adipiscing accumsan tempus, leo neque. Ut placerat at commodo accumsan, porta consectetur dictum.\r\nId vitae commodo lacus tellus. Tincidunt adipiscing bibendum turpis nam pellentesque quis leo. Sed viverra volutpat scelerisque eu morbi natoque non magna. Facilisis volutpat vel, tortor laoreet porttitor ullamcorper massa placerat diam. Iaculis varius lorem ullamcorper a in nulla dolor gravida feugiat. Pharetra justo et pellentesque nunc pretium ut blandit ultricies porttitor. Lacinia sit congue dui ante neque, enim duis id. Auctor nullam purus enim quam posuere.\r\nEros vestibulum nisl quam est luctus fames consectetur bibendum. Nunc, blandit nibh dui cursus metus mi vulputate. Risus sed eu vitae viverra mi congue proin vulputate. Sociis volutpat cursus et adipiscing auctor. Elit magna lacus quis sit fermentum. Eget praesent tellus non nulla.\r\nMassa et congue non dictum. Egestas cursus arcu proin sed in. Eros, volutpat odio in in diam accumsan. Semper sed hac id in ipsum in. Massa malesuada ac mauris consequat. Gravida tincidunt a pellentesque posuere amet pulvinar egestas. Ipsum orci aliquet urna, vitae egestas. Turpis leo magna ultrices odio proin semper tempus. Sem sit sit sed turpis eu donec quis. Dui sed pellentesque scelerisque etiam sollicitudin.\r\nVel volutpat bibendum ullamcorper commodo tempor quam sed arcu malesuada. At dignissim mattis ornare sem turpis dictum ultrices mi sed. Arcu in condimentum urna, molestie mattis. Cursus nulla cursus gravida porttitor diam, neque enim, sit. Pretium vulputate pellentesque purus sociis pellentesque egestas est urna.\r\nArcu adipiscing consequat, sit felis dictum. Amet adipiscing ut nibh at nibh. Id gravida lectus praesent neque eu lectus quisque. Dolor faucibus leo, at consequat neque. Risus mi sed augue diam. Libero molestie nulla sociis nisl massa libero, sollicitudin. Ut morbi etiam ut massa malesuada. Tristique tellus adipiscing diam sed. ', '.\\img\\04_fujiyoshida.jpg', 4, 1),
(5, 'Sydney', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tellus non pellentesque molestie dui mauris faucibus sit. Lacus mauris, integer dignissim mauris. Mattis tempor enim diam et sapien. Volutpat sit sapien faucibus aliquam. Velit tortor vivamus lectus fusce. Aliquam, enim phasellus a et, pellentesque. Bibendum est adipiscing dolor mattis tellus vel. Ut amet in vitae consequat amet. Pharetra vel porta posuere velit arcu aenean eget. Morbi quis massa euismod nunc fusce sit nulla leo. Aliquam et massa ac urna, sem tristique habitant pellentesque. Nec magna risus quis tincidunt fermentum ut id sed. Cursus adipiscing accumsan tempus, leo neque. Ut placerat at commodo accumsan, porta consectetur dictum.\r\nId vitae commodo lacus tellus. Tincidunt adipiscing bibendum turpis nam pellentesque quis leo. Sed viverra volutpat scelerisque eu morbi natoque non magna. Facilisis volutpat vel, tortor laoreet porttitor ullamcorper massa placerat diam. Iaculis varius lorem ullamcorper a in nulla dolor gravida feugiat. Pharetra justo et pellentesque nunc pretium ut blandit ultricies porttitor. Lacinia sit congue dui ante neque, enim duis id. Auctor nullam purus enim quam posuere.\r\nEros vestibulum nisl quam est luctus fames consectetur bibendum. Nunc, blandit nibh dui cursus metus mi vulputate. Risus sed eu vitae viverra mi congue proin vulputate. Sociis volutpat cursus et adipiscing auctor. Elit magna lacus quis sit fermentum. Eget praesent tellus non nulla.\r\nMassa et congue non dictum. Egestas cursus arcu proin sed in. Eros, volutpat odio in in diam accumsan. Semper sed hac id in ipsum in. Massa malesuada ac mauris consequat. Gravida tincidunt a pellentesque posuere amet pulvinar egestas. Ipsum orci aliquet urna, vitae egestas. Turpis leo magna ultrices odio proin semper tempus. Sem sit sit sed turpis eu donec quis. Dui sed pellentesque scelerisque etiam sollicitudin.\r\nVel volutpat bibendum ullamcorper commodo tempor quam sed arcu malesuada. At dignissim mattis ornare sem turpis dictum ultrices mi sed. Arcu in condimentum urna, molestie mattis. Cursus nulla cursus gravida porttitor diam, neque enim, sit. Pretium vulputate pellentesque purus sociis pellentesque egestas est urna.\r\nArcu adipiscing consequat, sit felis dictum. Amet adipiscing ut nibh at nibh. Id gravida lectus praesent neque eu lectus quisque. Dolor faucibus leo, at consequat neque. Risus mi sed augue diam. Libero molestie nulla sociis nisl massa libero, sollicitudin. Ut morbi etiam ut massa malesuada. Tristique tellus adipiscing diam sed. ', '.\\img\\05_sydney.jpg', 5, 1),
(6, 'Machu Picchu', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tellus non pellentesque molestie dui mauris faucibus sit. Lacus mauris, integer dignissim mauris. Mattis tempor enim diam et sapien. Volutpat sit sapien faucibus aliquam. Velit tortor vivamus lectus fusce. Aliquam, enim phasellus a et, pellentesque. Bibendum est adipiscing dolor mattis tellus vel. Ut amet in vitae consequat amet. Pharetra vel porta posuere velit arcu aenean eget. Morbi quis massa euismod nunc fusce sit nulla leo. Aliquam et massa ac urna, sem tristique habitant pellentesque. Nec magna risus quis tincidunt fermentum ut id sed. Cursus adipiscing accumsan tempus, leo neque. Ut placerat at commodo accumsan, porta consectetur dictum.\r\nId vitae commodo lacus tellus. Tincidunt adipiscing bibendum turpis nam pellentesque quis leo. Sed viverra volutpat scelerisque eu morbi natoque non magna. Facilisis volutpat vel, tortor laoreet porttitor ullamcorper massa placerat diam. Iaculis varius lorem ullamcorper a in nulla dolor gravida feugiat. Pharetra justo et pellentesque nunc pretium ut blandit ultricies porttitor. Lacinia sit congue dui ante neque, enim duis id. Auctor nullam purus enim quam posuere.\r\nEros vestibulum nisl quam est luctus fames consectetur bibendum. Nunc, blandit nibh dui cursus metus mi vulputate. Risus sed eu vitae viverra mi congue proin vulputate. Sociis volutpat cursus et adipiscing auctor. Elit magna lacus quis sit fermentum. Eget praesent tellus non nulla.\r\nMassa et congue non dictum. Egestas cursus arcu proin sed in. Eros, volutpat odio in in diam accumsan. Semper sed hac id in ipsum in. Massa malesuada ac mauris consequat. Gravida tincidunt a pellentesque posuere amet pulvinar egestas. Ipsum orci aliquet urna, vitae egestas. Turpis leo magna ultrices odio proin semper tempus. Sem sit sit sed turpis eu donec quis. Dui sed pellentesque scelerisque etiam sollicitudin.\r\nVel volutpat bibendum ullamcorper commodo tempor quam sed arcu malesuada. At dignissim mattis ornare sem turpis dictum ultrices mi sed. Arcu in condimentum urna, molestie mattis. Cursus nulla cursus gravida porttitor diam, neque enim, sit. Pretium vulputate pellentesque purus sociis pellentesque egestas est urna.\r\nArcu adipiscing consequat, sit felis dictum. Amet adipiscing ut nibh at nibh. Id gravida lectus praesent neque eu lectus quisque. Dolor faucibus leo, at consequat neque. Risus mi sed augue diam. Libero molestie nulla sociis nisl massa libero, sollicitudin. Ut morbi etiam ut massa malesuada. Tristique tellus adipiscing diam sed. ', '.\\img\\06_machu_picchu.jpg', 3, 1),
(7, 'Paris', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tellus non pellentesque molestie dui mauris faucibus sit. Lacus mauris, integer dignissim mauris. Mattis tempor enim diam et sapien. Volutpat sit sapien faucibus aliquam. Velit tortor vivamus lectus fusce. Aliquam, enim phasellus a et, pellentesque. Bibendum est adipiscing dolor mattis tellus vel. Ut amet in vitae consequat amet. Pharetra vel porta posuere velit arcu aenean eget. Morbi quis massa euismod nunc fusce sit nulla leo. Aliquam et massa ac urna, sem tristique habitant pellentesque. Nec magna risus quis tincidunt fermentum ut id sed. Cursus adipiscing accumsan tempus, leo neque. Ut placerat at commodo accumsan, porta consectetur dictum.\r\nId vitae commodo lacus tellus. Tincidunt adipiscing bibendum turpis nam pellentesque quis leo. Sed viverra volutpat scelerisque eu morbi natoque non magna. Facilisis volutpat vel, tortor laoreet porttitor ullamcorper massa placerat diam. Iaculis varius lorem ullamcorper a in nulla dolor gravida feugiat. Pharetra justo et pellentesque nunc pretium ut blandit ultricies porttitor. Lacinia sit congue dui ante neque, enim duis id. Auctor nullam purus enim quam posuere.\r\nEros vestibulum nisl quam est luctus fames consectetur bibendum. Nunc, blandit nibh dui cursus metus mi vulputate. Risus sed eu vitae viverra mi congue proin vulputate. Sociis volutpat cursus et adipiscing auctor. Elit magna lacus quis sit fermentum. Eget praesent tellus non nulla.\r\nMassa et congue non dictum. Egestas cursus arcu proin sed in. Eros, volutpat odio in in diam accumsan. Semper sed hac id in ipsum in. Massa malesuada ac mauris consequat. Gravida tincidunt a pellentesque posuere amet pulvinar egestas. Ipsum orci aliquet urna, vitae egestas. Turpis leo magna ultrices odio proin semper tempus. Sem sit sit sed turpis eu donec quis. Dui sed pellentesque scelerisque etiam sollicitudin.\r\nVel volutpat bibendum ullamcorper commodo tempor quam sed arcu malesuada. At dignissim mattis ornare sem turpis dictum ultrices mi sed. Arcu in condimentum urna, molestie mattis. Cursus nulla cursus gravida porttitor diam, neque enim, sit. Pretium vulputate pellentesque purus sociis pellentesque egestas est urna.\r\nArcu adipiscing consequat, sit felis dictum. Amet adipiscing ut nibh at nibh. Id gravida lectus praesent neque eu lectus quisque. Dolor faucibus leo, at consequat neque. Risus mi sed augue diam. Libero molestie nulla sociis nisl massa libero, sollicitudin. Ut morbi etiam ut massa malesuada. Tristique tellus adipiscing diam sed. ', '.\\img\\07_paris.jpg', 1, 1),
(8, 'Gizeh', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tellus non pellentesque molestie dui mauris faucibus sit. Lacus mauris, integer dignissim mauris. Mattis tempor enim diam et sapien. Volutpat sit sapien faucibus aliquam. Velit tortor vivamus lectus fusce. Aliquam, enim phasellus a et, pellentesque. Bibendum est adipiscing dolor mattis tellus vel. Ut amet in vitae consequat amet. Pharetra vel porta posuere velit arcu aenean eget. Morbi quis massa euismod nunc fusce sit nulla leo. Aliquam et massa ac urna, sem tristique habitant pellentesque. Nec magna risus quis tincidunt fermentum ut id sed. Cursus adipiscing accumsan tempus, leo neque. Ut placerat at commodo accumsan, porta consectetur dictum.\r\nId vitae commodo lacus tellus. Tincidunt adipiscing bibendum turpis nam pellentesque quis leo. Sed viverra volutpat scelerisque eu morbi natoque non magna. Facilisis volutpat vel, tortor laoreet porttitor ullamcorper massa placerat diam. Iaculis varius lorem ullamcorper a in nulla dolor gravida feugiat. Pharetra justo et pellentesque nunc pretium ut blandit ultricies porttitor. Lacinia sit congue dui ante neque, enim duis id. Auctor nullam purus enim quam posuere.\r\nEros vestibulum nisl quam est luctus fames consectetur bibendum. Nunc, blandit nibh dui cursus metus mi vulputate. Risus sed eu vitae viverra mi congue proin vulputate. Sociis volutpat cursus et adipiscing auctor. Elit magna lacus quis sit fermentum. Eget praesent tellus non nulla.\r\nMassa et congue non dictum. Egestas cursus arcu proin sed in. Eros, volutpat odio in in diam accumsan. Semper sed hac id in ipsum in. Massa malesuada ac mauris consequat. Gravida tincidunt a pellentesque posuere amet pulvinar egestas. Ipsum orci aliquet urna, vitae egestas. Turpis leo magna ultrices odio proin semper tempus. Sem sit sit sed turpis eu donec quis. Dui sed pellentesque scelerisque etiam sollicitudin.\r\nVel volutpat bibendum ullamcorper commodo tempor quam sed arcu malesuada. At dignissim mattis ornare sem turpis dictum ultrices mi sed. Arcu in condimentum urna, molestie mattis. Cursus nulla cursus gravida porttitor diam, neque enim, sit. Pretium vulputate pellentesque purus sociis pellentesque egestas est urna.\r\nArcu adipiscing consequat, sit felis dictum. Amet adipiscing ut nibh at nibh. Id gravida lectus praesent neque eu lectus quisque. Dolor faucibus leo, at consequat neque. Risus mi sed augue diam. Libero molestie nulla sociis nisl massa libero, sollicitudin. Ut morbi etiam ut massa malesuada. Tristique tellus adipiscing diam sed. ', '.\\img\\08_gizeh.jpg', 2, 1),
(9, 'Bali', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tellus non pellentesque molestie dui mauris faucibus sit. Lacus mauris, integer dignissim mauris. Mattis tempor enim diam et sapien. Volutpat sit sapien faucibus aliquam. Velit tortor vivamus lectus fusce. Aliquam, enim phasellus a et, pellentesque. Bibendum est adipiscing dolor mattis tellus vel. Ut amet in vitae consequat amet. Pharetra vel porta posuere velit arcu aenean eget. Morbi quis massa euismod nunc fusce sit nulla leo. Aliquam et massa ac urna, sem tristique habitant pellentesque. Nec magna risus quis tincidunt fermentum ut id sed. Cursus adipiscing accumsan tempus, leo neque. Ut placerat at commodo accumsan, porta consectetur dictum.\r\nId vitae commodo lacus tellus. Tincidunt adipiscing bibendum turpis nam pellentesque quis leo. Sed viverra volutpat scelerisque eu morbi natoque non magna. Facilisis volutpat vel, tortor laoreet porttitor ullamcorper massa placerat diam. Iaculis varius lorem ullamcorper a in nulla dolor gravida feugiat. Pharetra justo et pellentesque nunc pretium ut blandit ultricies porttitor. Lacinia sit congue dui ante neque, enim duis id. Auctor nullam purus enim quam posuere.\r\nEros vestibulum nisl quam est luctus fames consectetur bibendum. Nunc, blandit nibh dui cursus metus mi vulputate. Risus sed eu vitae viverra mi congue proin vulputate. Sociis volutpat cursus et adipiscing auctor. Elit magna lacus quis sit fermentum. Eget praesent tellus non nulla.\r\nMassa et congue non dictum. Egestas cursus arcu proin sed in. Eros, volutpat odio in in diam accumsan. Semper sed hac id in ipsum in. Massa malesuada ac mauris consequat. Gravida tincidunt a pellentesque posuere amet pulvinar egestas. Ipsum orci aliquet urna, vitae egestas. Turpis leo magna ultrices odio proin semper tempus. Sem sit sit sed turpis eu donec quis. Dui sed pellentesque scelerisque etiam sollicitudin.\r\nVel volutpat bibendum ullamcorper commodo tempor quam sed arcu malesuada. At dignissim mattis ornare sem turpis dictum ultrices mi sed. Arcu in condimentum urna, molestie mattis. Cursus nulla cursus gravida porttitor diam, neque enim, sit. Pretium vulputate pellentesque purus sociis pellentesque egestas est urna.\r\nArcu adipiscing consequat, sit felis dictum. Amet adipiscing ut nibh at nibh. Id gravida lectus praesent neque eu lectus quisque. Dolor faucibus leo, at consequat neque. Risus mi sed augue diam. Libero molestie nulla sociis nisl massa libero, sollicitudin. Ut morbi etiam ut massa malesuada. Tristique tellus adipiscing diam sed. ', '.\\img\\09_bali.jpg', 4, 1),
(10, 'Aoraki', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tellus non pellentesque molestie dui mauris faucibus sit. Lacus mauris, integer dignissim mauris. Mattis tempor enim diam et sapien. Volutpat sit sapien faucibus aliquam. Velit tortor vivamus lectus fusce. Aliquam, enim phasellus a et, pellentesque. Bibendum est adipiscing dolor mattis tellus vel. Ut amet in vitae consequat amet. Pharetra vel porta posuere velit arcu aenean eget. Morbi quis massa euismod nunc fusce sit nulla leo. Aliquam et massa ac urna, sem tristique habitant pellentesque. Nec magna risus quis tincidunt fermentum ut id sed. Cursus adipiscing accumsan tempus, leo neque. Ut placerat at commodo accumsan, porta consectetur dictum.\r\nId vitae commodo lacus tellus. Tincidunt adipiscing bibendum turpis nam pellentesque quis leo. Sed viverra volutpat scelerisque eu morbi natoque non magna. Facilisis volutpat vel, tortor laoreet porttitor ullamcorper massa placerat diam. Iaculis varius lorem ullamcorper a in nulla dolor gravida feugiat. Pharetra justo et pellentesque nunc pretium ut blandit ultricies porttitor. Lacinia sit congue dui ante neque, enim duis id. Auctor nullam purus enim quam posuere.\r\nEros vestibulum nisl quam est luctus fames consectetur bibendum. Nunc, blandit nibh dui cursus metus mi vulputate. Risus sed eu vitae viverra mi congue proin vulputate. Sociis volutpat cursus et adipiscing auctor. Elit magna lacus quis sit fermentum. Eget praesent tellus non nulla.\r\nMassa et congue non dictum. Egestas cursus arcu proin sed in. Eros, volutpat odio in in diam accumsan. Semper sed hac id in ipsum in. Massa malesuada ac mauris consequat. Gravida tincidunt a pellentesque posuere amet pulvinar egestas. Ipsum orci aliquet urna, vitae egestas. Turpis leo magna ultrices odio proin semper tempus. Sem sit sit sed turpis eu donec quis. Dui sed pellentesque scelerisque etiam sollicitudin.\r\nVel volutpat bibendum ullamcorper commodo tempor quam sed arcu malesuada. At dignissim mattis ornare sem turpis dictum ultrices mi sed. Arcu in condimentum urna, molestie mattis. Cursus nulla cursus gravida porttitor diam, neque enim, sit. Pretium vulputate pellentesque purus sociis pellentesque egestas est urna.\r\nArcu adipiscing consequat, sit felis dictum. Amet adipiscing ut nibh at nibh. Id gravida lectus praesent neque eu lectus quisque. Dolor faucibus leo, at consequat neque. Risus mi sed augue diam. Libero molestie nulla sociis nisl massa libero, sollicitudin. Ut morbi etiam ut massa malesuada. Tristique tellus adipiscing diam sed. ', '.\\img\\10_aoraki.jpg', 5, 1),
(35, 'Bagan', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tellus non pellentesque molestie dui mauris faucibus sit. Lacus mauris, integer dignissim mauris. Mattis tempor enim diam et sapien. Volutpat sit sapien faucibus aliquam. Velit tortor vivamus lectus fusce. Aliquam, enim phasellus a et, pellentesque. Bibendum est adipiscing dolor mattis tellus vel. Ut amet in vitae consequat amet. Pharetra vel porta posuere velit arcu aenean eget. Morbi quis massa euismod nunc fusce sit nulla leo. Aliquam et massa ac urna, sem tristique habitant pellentesque. Nec magna risus quis tincidunt fermentum ut id sed. Cursus adipiscing accumsan tempus, leo neque. Ut placerat at commodo accumsan, porta consectetur dictum.\r\nId vitae commodo lacus tellus. Tincidunt adipiscing bibendum turpis nam pellentesque quis leo. Sed viverra volutpat scelerisque eu morbi natoque non magna. Facilisis volutpat vel, tortor laoreet porttitor ullamcorper massa placerat diam. Iaculis varius lorem ullamcorper a in nulla dolor gravida feugiat. Pharetra justo et pellentesque nunc pretium ut blandit ultricies porttitor. Lacinia sit congue dui ante neque, enim duis id. Auctor nullam purus enim quam posuere.\r\nEros vestibulum nisl quam est luctus fames consectetur bibendum. Nunc, blandit nibh dui cursus metus mi vulputate. Risus sed eu vitae viverra mi congue proin vulputate. Sociis volutpat cursus et adipiscing auctor. Elit magna lacus quis sit fermentum. Eget praesent tellus non nulla.\r\nMassa et congue non dictum. Egestas cursus arcu proin sed in. Eros, volutpat odio in in diam accumsan. Semper sed hac id in ipsum in. Massa malesuada ac mauris consequat. Gravida tincidunt a pellentesque posuere amet pulvinar egestas. Ipsum orci aliquet urna, vitae egestas. Turpis leo magna ultrices odio proin semper tempus. Sem sit sit sed turpis eu donec quis. Dui sed pellentesque scelerisque etiam sollicitudin.\r\nVel volutpat bibendum ullamcorper commodo tempor quam sed arcu malesuada. At dignissim mattis ornare sem turpis dictum ultrices mi sed. Arcu in condimentum urna, molestie mattis. Cursus nulla cursus gravida porttitor diam, neque enim, sit. Pretium vulputate pellentesque purus sociis pellentesque egestas est urna.\r\nArcu adipiscing consequat, sit felis dictum. Amet adipiscing ut nibh at nibh. Id gravida lectus praesent neque eu lectus quisque. Dolor faucibus leo, at consequat neque. Risus mi sed augue diam. Libero molestie nulla sociis nisl massa libero, sollicitudin. Ut morbi etiam ut massa malesuada. Tristique tellus adipiscing diam sed. ', './img/bagan.jpg', 4, 1),
(36, 'Vanuatu', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tellus non pellentesque molestie dui mauris faucibus sit. Lacus mauris, integer dignissim mauris. Mattis tempor enim diam et sapien. Volutpat sit sapien faucibus aliquam. Velit tortor vivamus lectus fusce. Aliquam, enim phasellus a et, pellentesque. Bibendum est adipiscing dolor mattis tellus vel. Ut amet in vitae consequat amet. Pharetra vel porta posuere velit arcu aenean eget. Morbi quis massa euismod nunc fusce sit nulla leo. Aliquam et massa ac urna, sem tristique habitant pellentesque. Nec magna risus quis tincidunt fermentum ut id sed. Cursus adipiscing accumsan tempus, leo neque. Ut placerat at commodo accumsan, porta consectetur dictum.\r\nId vitae commodo lacus tellus. Tincidunt adipiscing bibendum turpis nam pellentesque quis leo. Sed viverra volutpat scelerisque eu morbi natoque non magna. Facilisis volutpat vel, tortor laoreet porttitor ullamcorper massa placerat diam. Iaculis varius lorem ullamcorper a in nulla dolor gravida feugiat. Pharetra justo et pellentesque nunc pretium ut blandit ultricies porttitor. Lacinia sit congue dui ante neque, enim duis id. Auctor nullam purus enim quam posuere.\r\nEros vestibulum nisl quam est luctus fames consectetur bibendum. Nunc, blandit nibh dui cursus metus mi vulputate. Risus sed eu vitae viverra mi congue proin vulputate. Sociis volutpat cursus et adipiscing auctor. Elit magna lacus quis sit fermentum. Eget praesent tellus non nulla.\r\nMassa et congue non dictum. Egestas cursus arcu proin sed in. Eros, volutpat odio in in diam accumsan. Semper sed hac id in ipsum in. Massa malesuada ac mauris consequat. Gravida tincidunt a pellentesque posuere amet pulvinar egestas. Ipsum orci aliquet urna, vitae egestas. Turpis leo magna ultrices odio proin semper tempus. Sem sit sit sed turpis eu donec quis. Dui sed pellentesque scelerisque etiam sollicitudin.\r\nVel volutpat bibendum ullamcorper commodo tempor quam sed arcu malesuada. At dignissim mattis ornare sem turpis dictum ultrices mi sed. Arcu in condimentum urna, molestie mattis. Cursus nulla cursus gravida porttitor diam, neque enim, sit. Pretium vulputate pellentesque purus sociis pellentesque egestas est urna.\r\nArcu adipiscing consequat, sit felis dictum. Amet adipiscing ut nibh at nibh. Id gravida lectus praesent neque eu lectus quisque. Dolor faucibus leo, at consequat neque. Risus mi sed augue diam. Libero molestie nulla sociis nisl massa libero, sollicitudin. Ut morbi etiam ut massa malesuada. Tristique tellus adipiscing diam sed. ', './img/vanuatu.jpg', 5, 1),
(38, 'Prague', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tellus non pellentesque molestie dui mauris faucibus sit. Lacus mauris, integer dignissim mauris. Mattis tempor enim diam et sapien. Volutpat sit sapien faucibus aliquam. Velit tortor vivamus lectus fusce. Aliquam, enim phasellus a et, pellentesque. Bibendum est adipiscing dolor mattis tellus vel. Ut amet in vitae consequat amet. Pharetra vel porta posuere velit arcu aenean eget. Morbi quis massa euismod nunc fusce sit nulla leo. Aliquam et massa ac urna, sem tristique habitant pellentesque. Nec magna risus quis tincidunt fermentum ut id sed. Cursus adipiscing accumsan tempus, leo neque. Ut placerat at commodo accumsan, porta consectetur dictum.\r\nId vitae commodo lacus tellus. Tincidunt adipiscing bibendum turpis nam pellentesque quis leo. Sed viverra volutpat scelerisque eu morbi natoque non magna. Facilisis volutpat vel, tortor laoreet porttitor ullamcorper massa placerat diam. Iaculis varius lorem ullamcorper a in nulla dolor gravida feugiat. Pharetra justo et pellentesque nunc pretium ut blandit ultricies porttitor. Lacinia sit congue dui ante neque, enim duis id. Auctor nullam purus enim quam posuere.\r\nEros vestibulum nisl quam est luctus fames consectetur bibendum. Nunc, blandit nibh dui cursus metus mi vulputate. Risus sed eu vitae viverra mi congue proin vulputate. Sociis volutpat cursus et adipiscing auctor. Elit magna lacus quis sit fermentum. Eget praesent tellus non nulla.\r\nMassa et congue non dictum. Egestas cursus arcu proin sed in. Eros, volutpat odio in in diam accumsan. Semper sed hac id in ipsum in. Massa malesuada ac mauris consequat. Gravida tincidunt a pellentesque posuere amet pulvinar egestas. Ipsum orci aliquet urna, vitae egestas. Turpis leo magna ultrices odio proin semper tempus. Sem sit sit sed turpis eu donec quis. Dui sed pellentesque scelerisque etiam sollicitudin.\r\nVel volutpat bibendum ullamcorper commodo tempor quam sed arcu malesuada. At dignissim mattis ornare sem turpis dictum ultrices mi sed. Arcu in condimentum urna, molestie mattis. Cursus nulla cursus gravida porttitor diam, neque enim, sit. Pretium vulputate pellentesque purus sociis pellentesque egestas est urna.\r\nArcu adipiscing consequat, sit felis dictum. Amet adipiscing ut nibh at nibh. Id gravida lectus praesent neque eu lectus quisque. Dolor faucibus leo, at consequat neque. Risus mi sed augue diam. Libero molestie nulla sociis nisl massa libero, sollicitudin. Ut morbi etiam ut massa malesuada. Tristique tellus adipiscing diam sed. ', './img/prague.jpg', 1, 1),
(39, 'Cape Town', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tellus non pellentesque molestie dui mauris faucibus sit. Lacus mauris, integer dignissim mauris. Mattis tempor enim diam et sapien. Volutpat sit sapien faucibus aliquam. Velit tortor vivamus lectus fusce. Aliquam, enim phasellus a et, pellentesque. Bibendum est adipiscing dolor mattis tellus vel. Ut amet in vitae consequat amet. Pharetra vel porta posuere velit arcu aenean eget. Morbi quis massa euismod nunc fusce sit nulla leo. Aliquam et massa ac urna, sem tristique habitant pellentesque. Nec magna risus quis tincidunt fermentum ut id sed. Cursus adipiscing accumsan tempus, leo neque. Ut placerat at commodo accumsan, porta consectetur dictum.\r\nId vitae commodo lacus tellus. Tincidunt adipiscing bibendum turpis nam pellentesque quis leo. Sed viverra volutpat scelerisque eu morbi natoque non magna. Facilisis volutpat vel, tortor laoreet porttitor ullamcorper massa placerat diam. Iaculis varius lorem ullamcorper a in nulla dolor gravida feugiat. Pharetra justo et pellentesque nunc pretium ut blandit ultricies porttitor. Lacinia sit congue dui ante neque, enim duis id. Auctor nullam purus enim quam posuere.\r\nEros vestibulum nisl quam est luctus fames consectetur bibendum. Nunc, blandit nibh dui cursus metus mi vulputate. Risus sed eu vitae viverra mi congue proin vulputate. Sociis volutpat cursus et adipiscing auctor. Elit magna lacus quis sit fermentum. Eget praesent tellus non nulla.\r\nMassa et congue non dictum. Egestas cursus arcu proin sed in. Eros, volutpat odio in in diam accumsan. Semper sed hac id in ipsum in. Massa malesuada ac mauris consequat. Gravida tincidunt a pellentesque posuere amet pulvinar egestas. Ipsum orci aliquet urna, vitae egestas. Turpis leo magna ultrices odio proin semper tempus. Sem sit sit sed turpis eu donec quis. Dui sed pellentesque scelerisque etiam sollicitudin.\r\nVel volutpat bibendum ullamcorper commodo tempor quam sed arcu malesuada. At dignissim mattis ornare sem turpis dictum ultrices mi sed. Arcu in condimentum urna, molestie mattis. Cursus nulla cursus gravida porttitor diam, neque enim, sit. Pretium vulputate pellentesque purus sociis pellentesque egestas est urna.\r\nArcu adipiscing consequat, sit felis dictum. Amet adipiscing ut nibh at nibh. Id gravida lectus praesent neque eu lectus quisque. Dolor faucibus leo, at consequat neque. Risus mi sed augue diam. Libero molestie nulla sociis nisl massa libero, sollicitudin. Ut morbi etiam ut massa malesuada. Tristique tellus adipiscing diam sed. ', './img/cape_town.jpg', 2, 1),
(40, 'Monument Valley', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tellus non pellentesque molestie dui mauris faucibus sit. Lacus mauris, integer dignissim mauris. Mattis tempor enim diam et sapien. Volutpat sit sapien faucibus aliquam. Velit tortor vivamus lectus fusce. Aliquam, enim phasellus a et, pellentesque. Bibendum est adipiscing dolor mattis tellus vel. Ut amet in vitae consequat amet. Pharetra vel porta posuere velit arcu aenean eget. Morbi quis massa euismod nunc fusce sit nulla leo. Aliquam et massa ac urna, sem tristique habitant pellentesque. Nec magna risus quis tincidunt fermentum ut id sed. Cursus adipiscing accumsan tempus, leo neque. Ut placerat at commodo accumsan, porta consectetur dictum.\r\nId vitae commodo lacus tellus. Tincidunt adipiscing bibendum turpis nam pellentesque quis leo. Sed viverra volutpat scelerisque eu morbi natoque non magna. Facilisis volutpat vel, tortor laoreet porttitor ullamcorper massa placerat diam. Iaculis varius lorem ullamcorper a in nulla dolor gravida feugiat. Pharetra justo et pellentesque nunc pretium ut blandit ultricies porttitor. Lacinia sit congue dui ante neque, enim duis id. Auctor nullam purus enim quam posuere.\r\nEros vestibulum nisl quam est luctus fames consectetur bibendum. Nunc, blandit nibh dui cursus metus mi vulputate. Risus sed eu vitae viverra mi congue proin vulputate. Sociis volutpat cursus et adipiscing auctor. Elit magna lacus quis sit fermentum. Eget praesent tellus non nulla.\r\nMassa et congue non dictum. Egestas cursus arcu proin sed in. Eros, volutpat odio in in diam accumsan. Semper sed hac id in ipsum in. Massa malesuada ac mauris consequat. Gravida tincidunt a pellentesque posuere amet pulvinar egestas. Ipsum orci aliquet urna, vitae egestas. Turpis leo magna ultrices odio proin semper tempus. Sem sit sit sed turpis eu donec quis. Dui sed pellentesque scelerisque etiam sollicitudin.\r\nVel volutpat bibendum ullamcorper commodo tempor quam sed arcu malesuada. At dignissim mattis ornare sem turpis dictum ultrices mi sed. Arcu in condimentum urna, molestie mattis. Cursus nulla cursus gravida porttitor diam, neque enim, sit. Pretium vulputate pellentesque purus sociis pellentesque egestas est urna.\r\nArcu adipiscing consequat, sit felis dictum. Amet adipiscing ut nibh at nibh. Id gravida lectus praesent neque eu lectus quisque. Dolor faucibus leo, at consequat neque. Risus mi sed augue diam. Libero molestie nulla sociis nisl massa libero, sollicitudin. Ut morbi etiam ut massa malesuada. Tristique tellus adipiscing diam sed. ', './img/monument-valley.jpg', 3, 1);

-- --------------------------------------------------------

--
-- Structure de la table `categories`
--

DROP TABLE IF EXISTS `categories`;
CREATE TABLE IF NOT EXISTS `categories` (
  `id_category` int NOT NULL AUTO_INCREMENT,
  `category` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `image_cat` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`id_category`)
) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `categories`
--

INSERT INTO `categories` (`id_category`, `category`, `image_cat`) VALUES
(1, 'Europe', './img/cat_01.jpg'),
(2, 'Afrique', './img/cat_02.jpg'),
(3, 'Amérique', './img/cat_03.jpg'),
(4, 'Asie', './img/cat_04.jpg'),
(5, 'Océanie', './img/cat_05.jpg');

-- --------------------------------------------------------

--
-- Structure de la table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id_user` int NOT NULL AUTO_INCREMENT,
  `username` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `password` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`id_user`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `users`
--

INSERT INTO `users` (`id_user`, `username`, `password`) VALUES
(1, 'warren', '$2y$10$1CRK0l.4kw2O0uT3HaLc1ublHO1UMgAWmIAmCzzTE7SaqS4MJhgNu');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
